addr: :8765
route:
  back:
    base: "/api"
  front:
    dir: "dist"
    index: "dist/index.html"
    admin: "dist/admin.html"
db:
  name: sonora
  host: postgres
  port: 5432
  username: onlyquant
storage:
  local:
    dir: "objects"
oidc:
  token_endpoint: "https://auth.onlyquant.top/api/oidc/token"
  userinfo_endpoint: "https://auth.onlyquant.top/api/oidc/userinfo"
  client_id: "mIzLmUyJA.8uXwtJYyqkyX_LS~LTpKm.VEqoOBbYgOQd2Q~iMBskX2OSMcqlZ7KEu4TaOzoB"
  redirect_uri: "https://sonora.onlyquant.top/oidc/callback"
